pluginManagement {
    repositories {
        maven {
          name = "stellardriftReleases"
          url = "https://repo.stellardrift.ca/maven/internal/"
          mavenContent { releasesOnly() }
        }
        maven {
            name = "stellardriftSnapshots"
            url = "https://repo.stellardrift.ca/maven/snapshots/"
            mavenContent { snapshotsOnly() }
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'gitpatcher'

dependencyResolutionManagement {
  repositoriesMode = RepositoriesMode.FAIL_ON_PROJECT_REPOS
  pluginManagement.repositories.each(repositories.&add)
}
