[metadata]
version = "1.0"

[versions]
indra = "4.1.0"
jspecify = "1.0.0"
junit = "6.0.0"
mammoth = "1.5.0"
spotless = "8.0.0"
pluginPublish = "2.0.0"

[libraries]
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mammoth-test = { module = "net.kyori:mammoth-test", version.ref = "mammoth" }

# testing

[plugins]
indra = { id = "net.kyori.indra", version.ref = "indra" }
indra-gradlePluginPublish = { id = "net.kyori.indra.publishing.gradle-plugin", version.ref = "indra" }
indra-licenserSpotless = { id = "net.kyori.indra.licenser.spotless", version.ref = "indra" }
pluginPublishPlugin = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }
sigstore = { id = "dev.sigstore.sign", version = "2.0.0-rc1" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
